//
//  TeamProtocols.swift
//  The Division
//
//  Created MTMAC16 on 14/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TeamWireframeProtocol: class {

}
//MARK: Presenter -
protocol TeamPresenterProtocol: class {

    var interactor: TeamInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol TeamInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol TeamInteractorInputProtocol: class {

    var presenter: TeamInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol TeamViewProtocol: class {

    var presenter: TeamPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
