//
//  TeamPresenter.swift
//  The Division
//
//  Created MTMAC16 on 14/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TeamPresenter: TeamPresenterProtocol, TeamInteractorOutputProtocol {

    weak private var view: TeamViewProtocol?
    var interactor: TeamInteractorInputProtocol?
    private let router: TeamWireframeProtocol

    init(interface: TeamViewProtocol, interactor: TeamInteractorInputProtocol?, router: TeamWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
