//
//  LoginInteractor.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginInteractor: LoginInteractorInputProtocol {
    var dataManager: LoginDataManagerInputProtocol?
    weak var presenter: LoginInteractorOutputProtocol?
    
    func login(email: String, password: String) {
        dataManager?.login(email: email, password: password)
    }
}

extension LoginInteractor: LoginDataManagerOutputProtocol {
    func showLoginSucceeded() {
        presenter?.showLoginSucceeded()
    }
    
    
}
