//
//  LoginPresenter.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginPresenter: LoginPresenterProtocol {
    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorInputProtocol?
    private let router: LoginWireframeProtocol

    init(interface: LoginViewProtocol, interactor: LoginInteractorInputProtocol?, router: LoginWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func login(email: String, password: String) {
        view?.showLoading()
        func isValidForm() -> Bool {
            return !email.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && !password.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
        
        if isValidForm() {
            interactor?.login(email: email, password: password)
        } else {
            view?.showError(with: "Please fill ur username and password")
        }
    }
    
    func goToHome() {
        router.goToHome()
    }
}

extension LoginPresenter: LoginInteractorOutputProtocol {
    func showLoginSucceeded() {
        view?.dismissLoading()
        view?.showLoginSucceeded()
    }
    
    
}
