//
//  LoginViewController.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: PortraitViewController {
    @IBOutlet var tfEmail: UITextField!
    @IBOutlet var tfPassword: UITextField!
    
	var presenter: LoginPresenterProtocol?

    override var shouldAutorotate: Bool {
        return true
    }
    
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return UIInterfaceOrientationMask.portrait
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        print("tes base url \(TheDivisionConstant.BASE_URL)")
        setupUI()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setupNavBar()
    }
    
    private func setupUI() {
        tfEmail.setLeftPaddingPoints(10)
        tfPassword.setLeftPaddingPoints(10)
    }
    
    private func setupNavBar() {
        navigationController?.navigationBar.isHidden = true
        navigationController?.navigationBar.barTintColor = #colorLiteral(red: 0.1490196078, green: 0.1607843137, blue: 0.1764705882, alpha: 1)
        self.navigationController?.navigationBar.tintColor = #colorLiteral(red: 1, green: 0.9921094184, blue: 0.3750105696, alpha: 1)
    }
    
    @IBAction func doRegister(_ sender: UIButton) {
        presenter?.goToRegister()
    }
    
    @IBAction func doLogin(_ sender: UIButton) {
        presenter?.login(email: tfEmail.text!, password: tfPassword.text!)
    }
}

extension LoginViewController: LoginViewProtocol {
    func showLoading() {
        HUDUtils.showLoading()
    }
    
    func showError(with message: String) {
        HUDUtils.showError(with: message)
    }
    
    func dismissLoading() {
        HUDUtils.dismiss()
    }
    
    func showLoginSucceeded() {
        presenter?.goToHome()
    }
}
