//
//  LoginRouter.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginRouter: LoginWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let navigation = AppStoryBoard.Main.instance.instantiateViewController(withIdentifier: Navigation.Login.rawValue)
        if let view = navigation.childViewControllers.first as? LoginViewController {
            
            let interactor = LoginInteractor()
            let router = LoginRouter()
            let dataManager = LoginDataManager()
            let presenter = LoginPresenter(interface: view, interactor: interactor, router: router)
            
            view.presenter = presenter
            interactor.presenter = presenter
            interactor.dataManager = dataManager
            dataManager.interactor = interactor
            router.viewController = view
            
            return navigation
        }
        
        return UIViewController()
    }
    
    static func createModuleAsRoot() {
        UIApplication.appDelegate.window?.rootViewController = createModule()
    }
}
