//
//  LoginViewController.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: UIViewController {
    @IBOutlet var tfEmail: UITextField!
    @IBOutlet var tfPassword: UITextField!
    
	var presenter: LoginPresenterProtocol?

    override var shouldAutorotate: Bool {
        return true
    }
    
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return UIInterfaceOrientationMask.portrait
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let value = UIInterfaceOrientation.portrait.rawValue
        UIDevice.current.setValue(value, forKey: "orientation")
        
    }

    @IBAction func doLogin(_ sender: UIButton) {
        presenter?.login(email: tfEmail.text!, password: tfPassword.text!)
    }
}

extension LoginViewController: LoginViewProtocol {
    func showLoginSucceeded() {
        let homeVC = AppStoryBoard.Home.instance.instantiateViewController(withIdentifier: "HomeViewController")
        UIApplication.appDelegate.window?.rootViewController = homeVC
    }
}
