//
//  IntroItemProtocols.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol IntroItemWireframeProtocol: class {
    /* Presenter -> Router */
    func goToLoginScreen(from view: IntroItemViewProtocol)
}
//MARK: Presenter -
protocol IntroItemPresenterProtocol: class {

    var interactor: IntroItemInteractorInputProtocol? { get set }
    
    /* ViewController -> Presenter */
    func goToLoginScreen()
}

//MARK: Interactor -
protocol IntroItemInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol IntroItemInteractorInputProtocol: class {

    var presenter: IntroItemInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol IntroItemViewProtocol: class {

    var presenter: IntroItemPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
