//
//  IntroItemPresenter.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class IntroItemPresenter: IntroItemPresenterProtocol, IntroItemInteractorOutputProtocol {

    weak private var view: IntroItemViewProtocol?
    var interactor: IntroItemInteractorInputProtocol?
    private let router: IntroItemWireframeProtocol

    init(interface: IntroItemViewProtocol, interactor: IntroItemInteractorInputProtocol?, router: IntroItemWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
