//
//  IntroItemViewController.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class IntroItemViewController: UIViewController, IntroItemViewProtocol {
    @IBOutlet var lbContent: UILabel!
    @IBOutlet var viewContainer: UIView!
    
    var content: String = ""
    var background: UIColor = .black
    
	var presenter: IntroItemPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        lbContent.text = content
        viewContainer.backgroundColor = background
        determineContentCollor()
    }
    
    private func determineContentCollor() {
        if viewContainer.backgroundColor == .white {
            lbContent.textColor = .black
        } else {
            lbContent.textColor = .white
        }
    }

}
