//
//  NotePresenter.swift
//  The Division
//
//  Created MTMAC16 on 28/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NotePresenter: NotePresenterProtocol, NoteInteractorOutputProtocol {

    weak private var view: NoteViewProtocol?
    var interactor: NoteInteractorInputProtocol?
    private let router: NoteWireframeProtocol

    init(interface: NoteViewProtocol, interactor: NoteInteractorInputProtocol?, router: NoteWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
