//
//  NoteViewController.swift
//  The Division
//
//  Created MTMAC16 on 28/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NoteViewController: LandscapeViewController, NoteViewProtocol {

    @IBOutlet var tableViewNotes: UITableView!
    
    var presenter: NotePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func addNote(_ sender: UIButton) {
        
    }
}
