//
//  ObjectiveViewController.swift
//  The Division
//
//  Created MTMAC16 on 28/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import M13Checkbox

class ObjectiveViewController: LandscapeViewController {
    @IBOutlet var tableViewObjective: UITableView!
    @IBOutlet var lbCompletion: UILabel!
    
    var presenter: ObjectivePresenterProtocol?
    var mission: Mission!
    var missionObjective: [Objective] = []

	override func viewDidLoad() {
        super.viewDidLoad()
        setupTableView()
        presenter?.getObjective(on: mission)
    }
    
    private func setupTableView() {
        tableViewObjective.delegate = self
        tableViewObjective.dataSource = self
        tableViewObjective.tableFooterView = UIView()
    }

    @IBAction func save(_ sender: UIButton) {
        presenter?.updateObjectives(with: missionObjective)
        dismiss(animated: true, completion: nil)
    }
    
    @IBAction func cancel(_ sender: UIButton) {
        dismiss(animated: true, completion: nil)
    }
}

extension ObjectiveViewController: ObjectiveViewProtocol {
    func onGetObjectiveSucceeded(with objectives: [Objective]) {
        missionObjective.append(contentsOf: objectives)
    }
    
    func onSaveObjectiveSucceeded(with objective: Objective) {
        
    }
}

extension ObjectiveViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return missionObjective.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let objective = missionObjective[indexPath.row]
        let cell = tableView.dequeueReusableCell(withIdentifier: "ObjectiveCell", for: indexPath) as! ObjectiveCell
        cell.bindDataToView(with: objective)
        cell.checkboxStateChange = { isChecked in
            print("is checked \(isChecked)")
            objective.isComplete = isChecked
        }
        
        return cell
    }
    
}

extension ObjectiveViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }
}
