 //
//  ObjectiveRouter.swift
//  The Division
//
//  Created MTMAC16 on 28/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ObjectiveRouter: ObjectiveWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(on mission: Mission) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = AppStoryBoard.Mission.instance.instantiateViewController(withIdentifier: MissionViewControllers.Objective.rawValue) as! ObjectiveViewController
        view.mission = mission
        let interactor = ObjectiveInteractor()
        let router = ObjectiveRouter()
        let dataManager = ObjectiveDataManager()
        let presenter = ObjectivePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        interactor.dataManager = dataManager
        dataManager.interactor = interactor

        return view
    }
}
