//
//  ObjectiveProtocols.swift
//  The Division
//
//  Created MTMAC16 on 28/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ObjectiveWireframeProtocol: class {

}
//MARK: Presenter -
protocol ObjectivePresenterProtocol: class {

    var interactor: ObjectiveInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol ObjectiveInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ObjectiveInteractorInputProtocol: class {

    var presenter: ObjectiveInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol ObjectiveViewProtocol: class {

    var presenter: ObjectivePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
