//
//  ObjectiveViewController.swift
//  The Division
//
//  Created MTMAC16 on 28/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import M13Checkbox

class ObjectiveViewController: LandscapeViewController {
    @IBOutlet var tableViewObjective: UITableView!
    @IBOutlet var lbCompletion: UILabel!
    @IBOutlet var lbObjectiveCount: UILabel!
    
    var presenter: ObjectivePresenterProtocol?
    var mission: Mission!
    var missionObjective: [Objective] = []
    var completedObjectiveCount: Int = 0 {
        didSet {
            lbObjectiveCount.text = "\(completedObjectiveCount)/\(missionObjective.count)"
        }
    }
    var dismissHandler: (() -> Void)!

	override func viewDidLoad() {
        super.viewDidLoad()
        setupTableView()
        setupUI()
        presenter?.getObjective(on: mission)
    }
    
    private func setupUI() {
        lbObjectiveCount.text = "0/\(missionObjective.count)"
    }
    
    private func setupTableView() {
        tableViewObjective.delegate = self
        tableViewObjective.dataSource = self
        tableViewObjective.tableFooterView = UIView()
    }

    @IBAction func save(_ sender: UIButton) {
        mission.objective = missionObjective
        presenter?.updateObjectives(with: missionObjective)
        
    }
    
    @IBAction func cancel(_ sender: UIButton) {
        dismiss(animated: true, completion: nil)
    }
}

extension ObjectiveViewController: ObjectiveViewProtocol {
    func onSucceedUpdateObjective() {
        dismiss(animated: true) {
            self.dismissHandler()
        }
    }
    
    func onGetObjectiveSucceeded(with objectives: [Objective]) {
        missionObjective.append(contentsOf: objectives)
    }
    
    func onSaveObjectiveSucceeded(with objective: Objective) {
        
    }
}

extension ObjectiveViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return missionObjective.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let objective = missionObjective[indexPath.row]
        if objective.isComplete {
            completedObjectiveCount += 1
        }
        let cell = tableView.dequeueReusableCell(withIdentifier: "ObjectiveCell", for: indexPath) as! ObjectiveCell
        cell.bindDataToView(with: objective)
        cell.checkboxStateChange = { isChecked in
            if isChecked {
                self.completedObjectiveCount += 1
            } else {
                self.completedObjectiveCount -= 1
            }
            objective.isComplete = isChecked
        }
        
        return cell
    }
    
}

extension ObjectiveViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }
}
