//
//  ObjectivePresenter.swift
//  The Division
//
//  Created MTMAC16 on 28/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ObjectivePresenter: ObjectivePresenterProtocol, ObjectiveInteractorOutputProtocol {

    weak private var view: ObjectiveViewProtocol?
    var interactor: ObjectiveInteractorInputProtocol?
    private let router: ObjectiveWireframeProtocol

    init(interface: ObjectiveViewProtocol, interactor: ObjectiveInteractorInputProtocol?, router: ObjectiveWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
