//
//  MissionDetailViewController.swift
//  The Division
//
//  Created MTMAC16 on 20/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MissionDetailViewController: UIViewController, MissionDetailViewProtocol {

	var presenter: MissionDetailPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
