//
//  TeamInteractor.swift
//  The Division
//
//  Created MTMAC16 on 14/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TeamInteractor: TeamInteractorInputProtocol {

    weak var presenter: TeamInteractorOutputProtocol?
    var dataManager: TeamDataManagerInputProtocol?
    
    func getTeamMember(on team: TeamDivision) {
        dataManager?.getTeamMember(on: team)
    }
    
    func addMember(with member: Member) {
        dataManager?.addMember(with: member)
    }
    
}

extension TeamInteractor: TeamDataManagerOutputProtocol {
    func onSuccessAddMember(with member: Member) {
        presenter?.onSuccessAddMember(with: member)
    }
    
    func onGetMemberSucceeded(with members: [Member]) {
        presenter?.onGetMemberSucceeded(with: members)
    }
    
    
}
