//
//  HomeContainerInteractor.swift
//  The Division
//
//  Created MTMAC16 on 14/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeContainerInteractor: HomeContainerInteractorInputProtocol {
    weak var presenter: HomeContainerInteractorOutputProtocol?
    var dataManager: HomeContainerDataManagerInputProtocol?
    
    func getMenuItem() {
        dataManager?.getMenuItem()
    }
}

extension HomeContainerInteractor: HomeContainerDataManagerOutputProtocol {
    func onGetMenuItemSucceed(menuItems: [[MenuItem]]) {
        presenter?.onGetMenuItemSucceed(menuItems: menuItems)
    }
}
