//
//  HomeContainerProtocols.swift
//  The Division
//
//  Created MTMAC16 on 14/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeContainerWireframeProtocol: class {

}
//MARK: Presenter -
protocol HomeContainerPresenterProtocol: class {

    var interactor: HomeContainerInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol HomeContainerInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol HomeContainerInteractorInputProtocol: class {

    var presenter: HomeContainerInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol HomeContainerViewProtocol: class {

    var presenter: HomeContainerPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
