//
//  HomeContainerPresenter.swift
//  The Division
//
//  Created MTMAC16 on 14/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeContainerPresenter: HomeContainerPresenterProtocol {
    weak private var view: HomeContainerViewProtocol?
    var interactor: HomeContainerInteractorInputProtocol?
    private let router: HomeContainerWireframeProtocol

    init(interface: HomeContainerViewProtocol, interactor: HomeContainerInteractorInputProtocol?, router: HomeContainerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getMenuItem() {
        interactor?.getMenuItem()
    }
    
}

extension HomeContainerPresenter: HomeContainerInteractorOutputProtocol {
    func onGetMenuItemSucceed(menuItems: [[MenuItem]]) {
        view?.onGetMenuItemSucceed(menuItems: menuItems)
    }
}
