//
//  HomeContainerInteractor.swift
//  The Division
//
//  Created MTMAC16 on 14/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeContainerInteractor: HomeContainerInteractorInputProtocol {

    weak var presenter: HomeContainerInteractorOutputProtocol?
}
