//
//  HomeContainerViewController.swift
//  The Division
//
//  Created MTMAC16 on 14/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeContainerViewController: UIViewController, HomeContainerViewProtocol {

    @IBOutlet var tablewViewMenu: UITableView!
    @IBOutlet var constraintMenuLeading: NSLayoutConstraint!
    
    var isMenuAppear: Bool = false
    var presenter: HomeContainerPresenterProtocol?

    override var shouldAutorotate: Bool {
        return true
    }
    
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return UIInterfaceOrientationMask.landscape
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let value = UIInterfaceOrientationMask.landscape.rawValue
        UIDevice.current.setValue(value, forKey: "orientation")
        
    }

    @IBAction func onGestureReaction(_ sender: UIScreenEdgePanGestureRecognizer) {
        let translation = sender.translation(in: view)
        var xTranslation = translation.x > self.tablewViewMenu.frame.width ? self.tablewViewMenu.frame.width : translation.x
        
        if xTranslation < (self.tablewViewMenu.frame.width / 3) && sender.state == .ended {
            xTranslation = -xTranslation
        } else if xTranslation > (self.tablewViewMenu.frame.width / 3) && sender.state == .ended {
            xTranslation = self.tablewViewMenu.frame.width
        }
        
        UIView.animate(withDuration: 0.3) {
            self.tablewViewMenu.transform = CGAffineTransform(translationX: xTranslation, y: self.tablewViewMenu.layer.anchorPoint.y)
        }
    }
    
    @IBAction func showDrawer(_ sender: UIButton) {
        if isMenuAppear {
            UIView.animate(withDuration: 0.3) {
                self.tablewViewMenu.transform = CGAffineTransform(translationX: -self.tablewViewMenu.frame.width, y: self.tablewViewMenu.layer.anchorPoint.y)
            }
        } else {
            UIView.animate(withDuration: 0.3) {
                self.tablewViewMenu.transform = CGAffineTransform(translationX: self.tablewViewMenu.frame.width, y: self.tablewViewMenu.layer.anchorPoint.y)
            }
        }
        
        isMenuAppear = !isMenuAppear
    }
}
