//
//  HomeContainerPresenter.swift
//  The Division
//
//  Created MTMAC16 on 14/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeContainerPresenter: HomeContainerPresenterProtocol, HomeContainerInteractorOutputProtocol {

    weak private var view: HomeContainerViewProtocol?
    var interactor: HomeContainerInteractorInputProtocol?
    private let router: HomeContainerWireframeProtocol

    init(interface: HomeContainerViewProtocol, interactor: HomeContainerInteractorInputProtocol?, router: HomeContainerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
