//
//  RegisterViewController.swift
//  The Division
//
//  Created MTMAC16 on 31/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegisterViewController: PortraitViewController {
    @IBOutlet var tfEmail: UITextField!
    @IBOutlet var tfUsername: UITextField!
    @IBOutlet var tfPassword: UITextField!
    @IBOutlet var tfPasswordConfirmation: UITextField!
    
	var presenter: RegisterPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setupNavBar()
    }
    
    private func setupNavBar() {
        navigationController?.navigationBar.isHidden = false
    }

    @IBAction func register(_ sender: UIButton) {
        presenter?.register(name: tfUsername.text!, password: tfPassword.text!, passwordConfirmation: tfPasswordConfirmation.text!, email: tfEmail.text!)
    }
}

extension RegisterViewController: RegisterViewProtocol {
    func onRegisterError(with message: String) {
        HUDUtils.showError(with: message)
    }
    
    func showLoading() {
        HUDUtils.showLoading(with: "Registering")
    }
    
    func dismissLoading() {
        HUDUtils.dismiss()
    }
    
    func onRegisterSucceeded() {
        self.navigationController?.popViewController(animated: true)
        HUDUtils.showInfo(with: "Registration success. Please login with your account")
        print("register succeeded")
    }
}
