//
//  RegisterInteractor.swift
//  The Division
//
//  Created MTMAC16 on 31/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RegisterInteractor: RegisterInteractorInputProtocol {
    var dataManager: RegisterDataManagerInputProtocol?
    weak var presenter: RegisterInteractorOutputProtocol?
    
    func register(name: String, password: String, passwordConfirmation: String, email: String) {
        dataManager?.register(name: name, password: password, passwordConfirmation: passwordConfirmation, email: email)
    }
    
}

extension RegisterInteractor: RegisterDataManagerOutputProtocol {
    func onRegisterSucceeded() {
        presenter?.onRegisterSucceeded()
    }
    
    func onRegisterError(with message: String) {
        presenter?.onRegisterError(with: message)
    }
}
