//
//  MissionProtocols.swift
//  The Division
//
//  Created MTMAC16 on 16/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MissionWireframeProtocol: class {

}
//MARK: Presenter -
protocol MissionPresenterProtocol: class {

    var interactor: MissionInteractorInputProtocol? { get set }
    
    /* ViewController -> Peresenter */
    func getMission(with state: MissionState)
    func createMission(with name: String, description: String)
}

//MARK: Interactor -
protocol MissionInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func onGetMissionSucceeded(with missions: [Mission])
    func onCreateMissionSucceeded(with mission: Mission)
}

protocol MissionInteractorInputProtocol: class {

    var presenter: MissionInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func getMission(with state: MissionState)
    func createMission(with name: String, description: String)
}

//MARK: View -
protocol MissionViewProtocol: class {

    var presenter: MissionPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func onGetMissionSucceeded(with missions: [Mission])
    func onCreateMissionSucceeded(with mission: Mission)
}

//MARK: DataManager -
protocol MissionDataManagerInputProtocol: class {
    var interactor: MissionDataManagerOutputProtocol? { get set }
    
    /* Interactor -> DataManager */
    func getMission(with state: MissionState)
    func createMission(with name: String, description: String)
}

protocol MissionDataManagerOutputProtocol: class {
    /* DataManager -> Interactor */
    func onGetMissionSucceeded(with missions: [Mission])
    func onCreateMissionSucceeded(with mission: Mission)
}

public enum MissionState: String {
    case InProgress = "In Progress"
    case New = "New"
    case Finished = "Finished"
}
