//
//  MissionProtocols.swift
//  The Division
//
//  Created MTMAC16 on 16/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MissionWireframeProtocol: class {

}
//MARK: Presenter -
protocol MissionPresenterProtocol: class {

    var interactor: MissionInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol MissionInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MissionInteractorInputProtocol: class {

    var presenter: MissionInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MissionViewProtocol: class {

    var presenter: MissionPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
