//
//  MissionProtocols.swift
//  The Division
//
//  Created MTMAC16 on 16/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MissionWireframeProtocol: class {
    func openMissionDetail(from view: MissionViewProtocol, with mission: Mission)
    func presentCreateMissionPopup(from view: MissionViewProtocol, with agents: [Member])
}
//MARK: Presenter -
protocol MissionPresenterProtocol: class {

    var interactor: MissionInteractorInputProtocol? { get set }
    
    /* ViewController -> Peresenter */
    func getMission(with state: MissionState)
    func createMission(with name: String, description: String, assignee: Member)
    func editMission(with mission: Mission)
    func openMissionDetail(from view: MissionViewProtocol, with mission: Mission)
    func presentCreateMissionPopup(from view: MissionViewProtocol, with agents: [Member])
    func getAllAgent()
}

//MARK: Interactor -
protocol MissionInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func onGetMissionSucceeded(with missions: [Mission])
    func onCreateMissionSucceeded(with mission: Mission)
    func onGetAllAgentSuceeded(with agents: [Member])
}

protocol MissionInteractorInputProtocol: class {

    var presenter: MissionInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
    func editMission(with mission: Mission)
    func getMission(with state: MissionState)
    func createMission(with name: String, description: String, assignee: Member)
    func getAllAgent()
}

//MARK: View -
protocol MissionViewProtocol: class {

    var presenter: MissionPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func onGetMissionSucceeded(with missions: [Mission])
    func onCreateMissionSucceeded(with mission: Mission)
    func onGetAllAgentSucceed(with agents: [Member])
}

//MARK: DataManager -
protocol MissionDataManagerInputProtocol: class {
    var interactor: MissionDataManagerOutputProtocol? { get set }
    
    /* Interactor -> DataManager */
    func editMission(with mission: Mission)
    func getMission(with state: MissionState)
    func createMission(with name: String, description: String, assignee: Member)
    func getAllAgent()
}

protocol MissionDataManagerOutputProtocol: class {
    /* DataManager -> Interactor */
    func onGetMissionSucceeded(with missions: [Mission])
    func onCreateMissionSucceeded(with mission: Mission)
    func onGetAllAgentSucceeded(with agents: [Member])
}
