//
//  MissionInteractor.swift
//  The Division
//
//  Created MTMAC16 on 16/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MissionInteractor: MissionInteractorInputProtocol {
    weak var presenter: MissionInteractorOutputProtocol?
    var dataManager: MissionDataManagerInputProtocol?
    
    func getMission(with state: MissionState) {
        dataManager?.getMission(with: state)
    }
}

extension MissionInteractor: MissionDataManagerOutputProtocol {
    func onGetMissionSucceeded(with missions: [Mission]) {
        presenter?.onGetMissionSucceeded(with: missions)
    }
}
