//
//  MissionInteractor.swift
//  The Division
//
//  Created MTMAC16 on 16/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MissionInteractor: MissionInteractorInputProtocol {

    weak var presenter: MissionInteractorOutputProtocol?
    var dataManager: MissionDataManagerInputProtocol?
    
    func getMission(with state: MissionState) {
        dataManager?.getMission(with: state)
    }
    
    func createMission(with name: String, description: String, assignee: Member, objective: [Objective]) {
        dataManager?.createMission(with: name, description: description, assignee: assignee, objective: objective)
    }
    
    func editMission(with mission: Mission) {
        dataManager?.editMission(with: mission)
    }
    
    func getAllAgent() {
        dataManager?.getAllAgent()
    }
}

extension MissionInteractor: MissionDataManagerOutputProtocol {
    func onCreateMissionSucceeded(with mission: Mission) {
        presenter?.onCreateMissionSucceeded(with: mission)
    }
    
    func onGetMissionSucceeded(with missions: [Mission]) {
        presenter?.onGetMissionSucceeded(with: missions)
    }
    
    func onGetAllAgentSucceeded(with agents: [Member]) {
        presenter?.onGetAllAgentSuceeded(with: agents)
    }
}
