//
//  MissionInteractor.swift
//  The Division
//
//  Created MTMAC16 on 16/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MissionInteractor: MissionInteractorInputProtocol {

    weak var presenter: MissionInteractorOutputProtocol?
}
