//
//  IntroProtocols.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit
//MARK: Wireframe -
protocol IntroWireframeProtocol: class {

}
//MARK: Presenter -
protocol IntroPresenterProtocol: class {

    var interactor: IntroInteractorInputProtocol? { get set }
    
    /* ViewController -> Presenter */
    func getIntros()
}

//MARK: Interactor -
protocol IntroInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol IntroInteractorInputProtocol: class {

    var presenter: IntroInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol IntroViewProtocol: class {

    var presenter: IntroPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func showIntros(with viewControllers: [UIViewController])
}
