//
//  IntroPresenter.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class IntroPresenter: IntroPresenterProtocol, IntroInteractorOutputProtocol {
    weak private var view: IntroViewProtocol?
    var interactor: IntroInteractorInputProtocol?
    private let router: IntroWireframeProtocol

    init(interface: IntroViewProtocol, interactor: IntroInteractorInputProtocol?, router: IntroWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getIntros() {
        var intros: [UIViewController] = []
        intros.append(IntroItemRouter.createModule(content: "Welcome", background: .white, showStartButton: false))
        intros.append(IntroItemRouter.createModule(content: "To", background: .gray, showStartButton: false))
        intros.append(IntroItemRouter.createModule(content: "The Division", background: .black, showStartButton: true))
        view?.showIntros(with: intros)
    }

}
