//
//  IntroInteractor.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class IntroInteractor: IntroInteractorInputProtocol {

    weak var presenter: IntroInteractorOutputProtocol?
}
