//
//  IntroViewController.swift
//  The Division
//
//  Created MTMAC16 on 13/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class IntroViewController: UIPageViewController, IntroViewProtocol {
  
	var presenter: IntroPresenterProtocol?
    fileprivate var intros: [UIViewController] = []
    
    override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.getIntros()
        dataSource = self
    }

    
    func showIntros(with viewControllers: [UIViewController]) {
        intros.append(contentsOf: viewControllers)
        if let firstIntro = intros.first {
            setViewControllers([firstIntro], direction: .forward, animated: true, completion: nil)
        }
    }
}


extension IntroViewController: UIPageViewControllerDataSource {
    func pageViewController(_ pageViewController: UIPageViewController, viewControllerBefore viewController: UIViewController) -> UIViewController? {
        guard let introIndex = intros.index(of: viewController) else { return nil }
        let prevIndex = introIndex - 1
        
        guard prevIndex >= 0 else { return intros.last }
        guard intros.count > prevIndex else { return nil }
        
        return intros[prevIndex]
    }
    
    func pageViewController(_ pageViewController: UIPageViewController, viewControllerAfter viewController: UIViewController) -> UIViewController? {
        guard let introIndex = intros.index(of: viewController) else { return nil }
        let nextIndex = introIndex + 1
        
        guard nextIndex < intros.count else { return intros.first }
        guard intros.count > nextIndex else { return nil }
        
        return intros[nextIndex]
    }
    
    func presentationCount(for pageViewController: UIPageViewController) -> Int {
        return intros.count
    }
    
    func presentationIndex(for pageViewController: UIPageViewController) -> Int {
        return 0
    }
    
    
}
