//
//  MissionDetailProtocols.swift
//  The Division
//
//  Created MTMAC16 on 20/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MissionDetailWireframeProtocol: class {
    var presenter: MissionDetailWireframeOutputProtocol? { get set }
    
    /* Presenter -> Router */
    func presentObjective(from view: MissionDetailViewProtocol, on mission: Mission)
    func presentPartner(from view: MissionDetailViewProtocol, on mission: Mission)
}

protocol MissionDetailWireframeOutputProtocol: class {
    /* router presenter */
    func onFinishUpdateObjective()
}

//MARK: Presenter -
protocol MissionDetailPresenterProtocol: class {

    var interactor: MissionDetailInteractorInputProtocol? { get set }
    
    /* ViewController -> Presenter */
    func presentObjective(from view: MissionDetailViewProtocol, on: Mission)
    func presentPartner(from view: MissionDetailViewProtocol, on mission: Mission)
    func getUpdatedMission(from mission: Mission)
}

//MARK: Interactor -
protocol MissionDetailInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func onGetUpdatedMission(with mission: Mission?)
}

protocol MissionDetailInteractorInputProtocol: class {

    var presenter: MissionDetailInteractorOutputProtocol?  { get set }
    var dataManager: MissionDetailDataManagerInputProtocol? { get set }

    /* Presenter -> Interactor */
    func getUpdatedMission(from mission: Mission)
}

//MARK: View -
protocol MissionDetailViewProtocol: class {

    var presenter: MissionDetailPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func onFinishUpdateObjective()
    func onGetUpdatedMission(with mission: Mission?)
}

//MARK: DataManager-
protocol MissionDetailDataManagerInputProtocol: class {
    var interactor: MissionDetailDataManagerOutputProtocol? { get set }
    
    /* Interactor -> DataManager */
    func getUpdatedMission(from mission: Mission)
}

protocol MissionDetailDataManagerOutputProtocol: class {
    /* DataManager -> Interactor */
    func onGetUpdatedMission(with mission: Mission?)
}
