//
//  MissionDetailViewController.swift
//  The Division
//
//  Created MTMAC16 on 20/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MissionDetailViewController: UIViewController {
    
    @IBOutlet var ivAgentAvatar: UIImageView!
    @IBOutlet var lbAgentName: UILabel!
    @IBOutlet var lbMissionName: UILabel!
    @IBOutlet var lbMissionDescription: UILabel!
    @IBOutlet var lbMisisonProgress: UILabel!
    @IBOutlet var viewMissionDetailContainer: UIView!
    
	var presenter: MissionDetailPresenterProtocol?
    var mission: Mission!

	override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        bindDataToView()
    }
    
    @IBAction func showNote(_ sender: UIButton) {
        presenter?.presentNote()
    }
    
    @IBAction func showPartner(_ sender: UIButton) {
        presenter?.presentPartner(from: self, on: mission)
    }
    
    @IBAction func showObjective(_ sender: UIButton) {
        presenter?.presentObjective(from: self, on: mission)
    }
    
    private func setupUI() {
        viewMissionDetailContainer.layer.shadowOpacity = 0.7
        viewMissionDetailContainer.layer.shadowColor = UIColor.yellow.cgColor
        viewMissionDetailContainer.layer.shadowRadius = 10
    }

    private func bindDataToView() {
        //MARK: TODO render avatar and agent data
        lbMissionName.text = mission.name
        lbMissionDescription.text = mission.description
        lbAgentName.text = mission.assignee?.name ?? "-"
        ivAgentAvatar.image = mission.assignee?.pict
        lbMisisonProgress.text = "\(Int(mission.progress))%"
    }
}

extension MissionDetailViewController: MissionDetailViewProtocol {
    func onGetUpdatedMission(with mission: Mission?) {
        if let updatedMission = mission {
            self.mission = updatedMission
            bindDataToView()
        }
    }
    
    func onFinishUpdateObjective() {
        presenter?.getUpdatedMission(from: mission)
    }
    
}
