//
//  PartnerViewController.swift
//  The Division
//
//  Created MTMAC16 on 28/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PartnerViewController: LandscapeViewController, PartnerViewProtocol {

	var presenter: PartnerPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
