//
//  MissionDetailInteractor.swift
//  The Division
//
//  Created MTMAC16 on 20/08/18.
//  Copyright © 2018 bism. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MissionDetailInteractor: MissionDetailInteractorInputProtocol {

    weak var presenter: MissionDetailInteractorOutputProtocol?
}
